# Apply AFTER overlay-1mm.conf for first-touch testing.
# Enable an appropriate logging backend in the keyboard configuration.
CONFIG_LOG=y
CONFIG_INPUT_IQS9151_LOG_LEVEL=4
CONFIG_INPUT_IQS9151_CURSOR_INERTIA_ENABLE=n
CONFIG_INPUT_IQS9151_SCROLL_INERTIA_ENABLE=n
CONFIG_INPUT_IQS9151_1F_TAP_ENABLE=n
CONFIG_INPUT_IQS9151_1F_PRESSHOLD_ENABLE=n
CONFIG_INPUT_IQS9151_2F_TAP_ENABLE=n
CONFIG_INPUT_IQS9151_2F_PRESSHOLD_ENABLE=n
CONFIG_INPUT_IQS9151_2F_PINCH_ENABLE=n
CONFIG_INPUT_IQS9151_3F_TAP_ENABLE=n
CONFIG_INPUT_IQS9151_3F_PRESSHOLD_ENABLE=n
