/* SPDX-License-Identifier: MIT */
#ifndef IQS9151_PROFILE_H
#define IQS9151_PROFILE_H
#include "iqs9151_init.h"
#ifdef CONFIG_INPUT_IQS9151_TPS43_A2
#include "profiles/tps43_a2.h"
#endif
/* Overlay tuning is independent of the PCB electrode geometry. */
#undef TRACKPAD_TOUCH_SET_THRESHOLD
#define TRACKPAD_TOUCH_SET_THRESHOLD CONFIG_INPUT_IQS9151_TOUCH_SET_THRESHOLD
#undef TRACKPAD_TOUCH_CLEAR_THRESHOLD
#define TRACKPAD_TOUCH_CLEAR_THRESHOLD CONFIG_INPUT_IQS9151_TOUCH_CLEAR_THRESHOLD
#undef ALP_THRESHOLD
#define ALP_THRESHOLD CONFIG_INPUT_IQS9151_ALP_THRESHOLD
#undef ALP_AUTOPROX_THRESHOLD
#define ALP_AUTOPROX_THRESHOLD CONFIG_INPUT_IQS9151_ALP_AUTOPROX_THRESHOLD
#endif
